arm_teleop_node:
  ros__parameters:
    # Axis Indicators
    axis_left_x: 0 # Base Rotation
    axis_left_y: 1 # Shoulder
    axis_right_x: 2 # Elbow
    axis_right_y: 5 # Forearm
    axis_l2: 3 # Gripper Close
    axis_r2: 4 # Gripper Open
    axis_dpad_x: 6 # Wrist Roll
    axis_dpad_y: 7 # Wrist Pitch

    # Button Indicators
    btn_enable: 0        # Cross - enable/disable
    btn_estop: 1         # Circle - e-stop
    btn_rearm: 9         # Options - re-arm after e-stop
    btn_speed: 4         # L1 - speed toggle

